server:
  port: 8800

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: nginx-service
          uri: http://nginx.edu25.svc.cluster.local
          predicates:
            - Path=/nginx/**
          filters:
            - RewritePath=/nginx/(?<path>.*),/$\{path}
        - id: httpd-service
          uri: http://httpd.edu25.svc.cluster.local
          predicates:
            - Path=/httpd/**
          filters:
            - RewritePath=/(?<path>.*),/$\{path}

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
    com.kt: trace
